[package]
name = "c_u_soon_instruction"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
c_u_soon = { path = "../sdk" }
wincode = { workspace = true }
