[package]
name = "attacker_probe"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
pinocchio = { git = "ssh://git@github.com/figaro-sol/pinocchio.git", branch = "small_oracle", features = ["cpi"] }

[lib]
crate-type = ["cdylib"]
